create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;

grant usage on schema private to service_role;

create table if not exists private.app_version_policies (
  id bigint generated by default as identity primary key,
  app_id text not null,
  environment text not null,
  platform text not null,
  min_supported_version text not null,
  latest_version text,
  min_os_version text,
  update_url text,
  force_message text,
  soft_message text,
  cache_ttl_seconds integer not null default 21600,
  is_enabled boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists app_version_policies_app_env_platform_uidx
  on private.app_version_policies (app_id, environment, platform);

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_app_version_policies_touch_updated_at
  on private.app_version_policies;

create trigger trg_app_version_policies_touch_updated_at
before update on private.app_version_policies
for each row
execute function private.touch_updated_at();

insert into private.app_version_policies (
  app_id,
  environment,
  platform,
  min_supported_version,
  latest_version,
  update_url,
  force_message,
  soft_message,
  cache_ttl_seconds,
  is_enabled
)
values
  (
    'movi',
    'prod',
    'android',
    '1.0.2',
    '1.0.2',
    'https://play.google.com/store/apps/details?id=com.matteo.movi',
    'Une mise à jour est requise pour continuer.',
    'Une version plus récente est disponible.',
    21600,
    true
  ),
  (
    'movi',
    'prod',
    'ios',
    '1.0.2',
    '1.0.2',
    null,
    'Une mise à jour est requise pour continuer.',
    'Une version plus récente est disponible.',
    21600,
    true
  )
on conflict (app_id, environment, platform) do nothing;
